name: CI

on:
  push: 
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@main
      
      - name: Install Dependencies   
        run: npm install

      - name: Build                   
        run: CI=false npm run build

      - name: Deploy to S3
        run: aws s3 sync build s3://${{ secrets.BUCKET_NAME }}
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.DISTRIBUTION_ID}} --paths "/*"
